// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.sdj3.app.protobuf;

public interface AnimalIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idOfAnimal = 1;</code>
   * @return The idOfAnimal.
   */
  int getIdOfAnimal();
}
