// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.sdj3.app.protobuf;

public final class Assign3 {
  private Assign3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NoParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NoParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListOfAnimals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListOfAnimals_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Origin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Origin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Date_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Date_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InvolvedAnimals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InvolvedAnimals_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InvolvedProducts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InvolvedProducts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rassign3.proto\"\t\n\007NoParam\"J\n\nAnimalGrpc" +
      "\022\016\n\006regNum\030\001 \001(\005\022\014\n\004date\030\002 \001(\t\022\016\n\006weight" +
      "\030\003 \001(\001\022\016\n\006origin\030\004 \001(\t\"-\n\rListOfAnimals\022" +
      "\034\n\007animals\030\001 \003(\0132\013.AnimalGrpc\"\030\n\006Origin\022" +
      "\016\n\006origin\030\002 \001(\t\"\024\n\004Date\022\014\n\004date\030\002 \001(\t\" \n" +
      "\tProductId\022\023\n\013idOfProduct\030\001 \001(\005\"\036\n\010Anima" +
      "lId\022\022\n\nidOfAnimal\030\001 \001(\005\"%\n\017InvolvedAnima" +
      "ls\022\022\n\nidOfAnimal\030\001 \003(\005\"\'\n\020InvolvedProduc" +
      "ts\022\023\n\013idOfProduct\030\001 \003(\0052\267\002\n\016Slaughterhou" +
      "se\022/\n\017retrieveRegNums\022\n.ProductId\032\020.Invo" +
      "lvedAnimals\0220\n\020retrieveProdNums\022\t.Animal" +
      "Id\032\021.InvolvedProducts\022(\n\014createAnimal\022\013." +
      "AnimalGrpc\032\013.AnimalGrpc\022)\n\rgetAllAnimals" +
      "\022\010.NoParam\032\016.ListOfAnimals\022!\n\007getById\022\t." +
      "AnimalId\032\013.AnimalGrpc\022&\n\013getByOrigin\022\007.O" +
      "rigin\032\016.ListOfAnimals\022\"\n\tgetByDate\022\005.Dat" +
      "e\032\016.ListOfAnimalsB\031\n\025via.sdj3.app.protob" +
      "ufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NoParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NoParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NoParam_descriptor,
        new java.lang.String[] { });
    internal_static_AnimalGrpc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnimalGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalGrpc_descriptor,
        new java.lang.String[] { "RegNum", "Date", "Weight", "Origin", });
    internal_static_ListOfAnimals_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ListOfAnimals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListOfAnimals_descriptor,
        new java.lang.String[] { "Animals", });
    internal_static_Origin_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Origin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Origin_descriptor,
        new java.lang.String[] { "Origin", });
    internal_static_Date_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Date_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Date_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_ProductId_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ProductId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductId_descriptor,
        new java.lang.String[] { "IdOfProduct", });
    internal_static_AnimalId_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalId_descriptor,
        new java.lang.String[] { "IdOfAnimal", });
    internal_static_InvolvedAnimals_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_InvolvedAnimals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InvolvedAnimals_descriptor,
        new java.lang.String[] { "IdOfAnimal", });
    internal_static_InvolvedProducts_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_InvolvedProducts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InvolvedProducts_descriptor,
        new java.lang.String[] { "IdOfProduct", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
