// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.sdj3.app.protobuf;

public interface ListOfAnimalsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOfAnimals)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AnimalGrpc animals = 1;</code>
   */
  java.util.List<via.sdj3.app.protobuf.AnimalGrpc> 
      getAnimalsList();
  /**
   * <code>repeated .AnimalGrpc animals = 1;</code>
   */
  via.sdj3.app.protobuf.AnimalGrpc getAnimals(int index);
  /**
   * <code>repeated .AnimalGrpc animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .AnimalGrpc animals = 1;</code>
   */
  java.util.List<? extends via.sdj3.app.protobuf.AnimalGrpcOrBuilder> 
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .AnimalGrpc animals = 1;</code>
   */
  via.sdj3.app.protobuf.AnimalGrpcOrBuilder getAnimalsOrBuilder(
      int index);
}
