// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.sdj3.app.protobuf;

public interface NoParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NoParam)
    com.google.protobuf.MessageOrBuilder {
}
