// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.sdj3.app.protobuf;

public interface OriginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Origin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string origin = 2;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 2;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();
}
