// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.group1.assign3.protobuf;

public interface InvolvedProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InvolvedProducts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 idOfProduct = 1;</code>
   * @return A list containing the idOfProduct.
   */
  java.util.List<java.lang.Integer> getIdOfProductList();
  /**
   * <code>repeated int32 idOfProduct = 1;</code>
   * @return The count of idOfProduct.
   */
  int getIdOfProductCount();
  /**
   * <code>repeated int32 idOfProduct = 1;</code>
   * @param index The index of the element to return.
   * @return The idOfProduct at the given index.
   */
  int getIdOfProduct(int index);
}
