// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.group1.assign3.protobuf;

public interface InvolvedAnimalsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InvolvedAnimals)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 idOfAnimal = 1;</code>
   * @return A list containing the idOfAnimal.
   */
  java.util.List<java.lang.Integer> getIdOfAnimalList();
  /**
   * <code>repeated int32 idOfAnimal = 1;</code>
   * @return The count of idOfAnimal.
   */
  int getIdOfAnimalCount();
  /**
   * <code>repeated int32 idOfAnimal = 1;</code>
   * @param index The index of the element to return.
   * @return The idOfAnimal at the given index.
   */
  int getIdOfAnimal(int index);
}
