// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.group1.assign3.protobuf;

/**
 * Protobuf type {@code InvolvedAnimals}
 */
public final class InvolvedAnimals extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InvolvedAnimals)
    InvolvedAnimalsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InvolvedAnimals.newBuilder() to construct.
  private InvolvedAnimals(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InvolvedAnimals() {
    idOfAnimal_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InvolvedAnimals();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InvolvedAnimals(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              idOfAnimal_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            idOfAnimal_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              idOfAnimal_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              idOfAnimal_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        idOfAnimal_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.group1.assign3.protobuf.Assign3.internal_static_InvolvedAnimals_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.group1.assign3.protobuf.Assign3.internal_static_InvolvedAnimals_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.group1.assign3.protobuf.InvolvedAnimals.class, via.group1.assign3.protobuf.InvolvedAnimals.Builder.class);
  }

  public static final int IDOFANIMAL_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList idOfAnimal_;
  /**
   * <code>repeated int32 idOfAnimal = 1;</code>
   * @return A list containing the idOfAnimal.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getIdOfAnimalList() {
    return idOfAnimal_;
  }
  /**
   * <code>repeated int32 idOfAnimal = 1;</code>
   * @return The count of idOfAnimal.
   */
  public int getIdOfAnimalCount() {
    return idOfAnimal_.size();
  }
  /**
   * <code>repeated int32 idOfAnimal = 1;</code>
   * @param index The index of the element to return.
   * @return The idOfAnimal at the given index.
   */
  public int getIdOfAnimal(int index) {
    return idOfAnimal_.getInt(index);
  }
  private int idOfAnimalMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getIdOfAnimalList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(idOfAnimalMemoizedSerializedSize);
    }
    for (int i = 0; i < idOfAnimal_.size(); i++) {
      output.writeInt32NoTag(idOfAnimal_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < idOfAnimal_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(idOfAnimal_.getInt(i));
      }
      size += dataSize;
      if (!getIdOfAnimalList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      idOfAnimalMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.group1.assign3.protobuf.InvolvedAnimals)) {
      return super.equals(obj);
    }
    via.group1.assign3.protobuf.InvolvedAnimals other = (via.group1.assign3.protobuf.InvolvedAnimals) obj;

    if (!getIdOfAnimalList()
        .equals(other.getIdOfAnimalList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIdOfAnimalCount() > 0) {
      hash = (37 * hash) + IDOFANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getIdOfAnimalList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.group1.assign3.protobuf.InvolvedAnimals parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.group1.assign3.protobuf.InvolvedAnimals prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InvolvedAnimals}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InvolvedAnimals)
      via.group1.assign3.protobuf.InvolvedAnimalsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.group1.assign3.protobuf.Assign3.internal_static_InvolvedAnimals_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.group1.assign3.protobuf.Assign3.internal_static_InvolvedAnimals_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.group1.assign3.protobuf.InvolvedAnimals.class, via.group1.assign3.protobuf.InvolvedAnimals.Builder.class);
    }

    // Construct using via.group1.assign3.protobuf.InvolvedAnimals.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idOfAnimal_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.group1.assign3.protobuf.Assign3.internal_static_InvolvedAnimals_descriptor;
    }

    @java.lang.Override
    public via.group1.assign3.protobuf.InvolvedAnimals getDefaultInstanceForType() {
      return via.group1.assign3.protobuf.InvolvedAnimals.getDefaultInstance();
    }

    @java.lang.Override
    public via.group1.assign3.protobuf.InvolvedAnimals build() {
      via.group1.assign3.protobuf.InvolvedAnimals result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.group1.assign3.protobuf.InvolvedAnimals buildPartial() {
      via.group1.assign3.protobuf.InvolvedAnimals result = new via.group1.assign3.protobuf.InvolvedAnimals(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        idOfAnimal_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.idOfAnimal_ = idOfAnimal_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.group1.assign3.protobuf.InvolvedAnimals) {
        return mergeFrom((via.group1.assign3.protobuf.InvolvedAnimals)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.group1.assign3.protobuf.InvolvedAnimals other) {
      if (other == via.group1.assign3.protobuf.InvolvedAnimals.getDefaultInstance()) return this;
      if (!other.idOfAnimal_.isEmpty()) {
        if (idOfAnimal_.isEmpty()) {
          idOfAnimal_ = other.idOfAnimal_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIdOfAnimalIsMutable();
          idOfAnimal_.addAll(other.idOfAnimal_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.group1.assign3.protobuf.InvolvedAnimals parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.group1.assign3.protobuf.InvolvedAnimals) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList idOfAnimal_ = emptyIntList();
    private void ensureIdOfAnimalIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        idOfAnimal_ = mutableCopy(idOfAnimal_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 idOfAnimal = 1;</code>
     * @return A list containing the idOfAnimal.
     */
    public java.util.List<java.lang.Integer>
        getIdOfAnimalList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(idOfAnimal_) : idOfAnimal_;
    }
    /**
     * <code>repeated int32 idOfAnimal = 1;</code>
     * @return The count of idOfAnimal.
     */
    public int getIdOfAnimalCount() {
      return idOfAnimal_.size();
    }
    /**
     * <code>repeated int32 idOfAnimal = 1;</code>
     * @param index The index of the element to return.
     * @return The idOfAnimal at the given index.
     */
    public int getIdOfAnimal(int index) {
      return idOfAnimal_.getInt(index);
    }
    /**
     * <code>repeated int32 idOfAnimal = 1;</code>
     * @param index The index to set the value at.
     * @param value The idOfAnimal to set.
     * @return This builder for chaining.
     */
    public Builder setIdOfAnimal(
        int index, int value) {
      ensureIdOfAnimalIsMutable();
      idOfAnimal_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 idOfAnimal = 1;</code>
     * @param value The idOfAnimal to add.
     * @return This builder for chaining.
     */
    public Builder addIdOfAnimal(int value) {
      ensureIdOfAnimalIsMutable();
      idOfAnimal_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 idOfAnimal = 1;</code>
     * @param values The idOfAnimal to add.
     * @return This builder for chaining.
     */
    public Builder addAllIdOfAnimal(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureIdOfAnimalIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, idOfAnimal_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 idOfAnimal = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdOfAnimal() {
      idOfAnimal_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InvolvedAnimals)
  }

  // @@protoc_insertion_point(class_scope:InvolvedAnimals)
  private static final via.group1.assign3.protobuf.InvolvedAnimals DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.group1.assign3.protobuf.InvolvedAnimals();
  }

  public static via.group1.assign3.protobuf.InvolvedAnimals getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InvolvedAnimals>
      PARSER = new com.google.protobuf.AbstractParser<InvolvedAnimals>() {
    @java.lang.Override
    public InvolvedAnimals parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InvolvedAnimals(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InvolvedAnimals> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InvolvedAnimals> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.group1.assign3.protobuf.InvolvedAnimals getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

