// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assign3.proto

package via.group1.assign3.protobuf;

public interface ProductIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idOfProduct = 1;</code>
   * @return The idOfProduct.
   */
  int getIdOfProduct();
}
